---
title: "bat_speed"
author: "Diego Martinez"
date: "6/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cache = TRUE)

# necessary packages 
library(dplyr)
library(tidyverse)
library(broom)
library(tidyverse)
library(skimr)
library(gt)


# loading in data, .csvs were previously written and saved into repository

metrics_2<-read_csv("metrics.csv")

max_evs<-read_csv("max_evs.csv")

# for loop for how I determined the launch angle at which players maximizes
# their exit velo. Takes awhile so I saved the results and they can be found
# above in max_evs.csv.

# Prior to this step I arranged the players by name and season, and then I
# arranged by launch angle. Their were 2376 player-seasons in the dataset
# 
# for (j in 1:2376) {
#   player <-player_season%>%
#      filter(player_number == j)
#    
#    x = tibble()
# 
# 
# 
#   for (i in 1:(nrow(player)-round((nrow(player)/8)))) {
#      y<-player%>%
#              slice(i:(i+round((nrow(player)/8))))%>%
#        mutate(avg_ev = mean(launch_speed),
#               avg_la = mean(launch_angle))
#      
#      x<-x%>%bind_rows(y)%>%
#        filter(avg_ev == max(avg_ev))
#    
#    }
#    max_evs<-max_evs%>%bind_rows(x)
# }



```


```{r building metrics dataset, eval=FALSE, echo=FALSE}

people<-read_csv("People.csv") 

ids_copy <- read_csv("ids copy.csv")%>%
  select(FANGRAPHSNAME, IDFANGRAPHS, bbrefID = BREFID)

people<-people%>%left_join(ids_copy, by = "bbrefID")%>%
  mutate(playerid = as.numeric(IDFANGRAPHS))%>%
  select(weight, height, playerid)%>%
  filter(!is.na(playerid))


advanced <- read_csv("advanced.csv")
batted_ball <- read_csv("batted_ball.csv")


ages <- read_csv("ages.csv")%>%
  select(Season, Name, Age, playerid)

ids<- read_csv("ids copy.csv")

ids<-ids%>%select(IDFANGRAPHS,MLBID)%>%
  mutate(playerid = as.numeric(IDFANGRAPHS), batter = MLBID)
  

defense <- read_csv("defense.csv")

plate_disc<-read_csv("plate_disc.csv")%>%
  mutate_if(is.character,topct)%>%
  select(-Team, -Name)

defense<-defense%>%
  select(playerid, Pos, GS)%>%
  group_by(playerid, Pos)%>%
  mutate(total_g = sum(GS))%>%
  arrange(playerid, desc(total_g))%>%
  ungroup()%>%
  group_by(playerid)%>%
  top_n(n =1)%>%
  select(playerid, Pos)%>%
  unique()
value <- read_csv("value.csv")

fangraphs<-ages%>%
  left_join(advanced, by = c("playerid", "Season"))%>%
  left_join(batted_ball, by = c("playerid", "Season"))%>%
  left_join(value, by = c("playerid", "Season"))%>%
  left_join(ids, by = "playerid")%>%
  left_join(defense, by = "playerid")%>%
  left_join(plate_disc, by = c("playerid", "Season"))%>%
  left_join(people, by = "playerid")

metrics<-fangraphs%>%
  select(Season,Name = Name.x, Age, playerid, PA, `K%`, ISO, wOBA,`LD%`,`GB%`,`FB%`,`Soft%`,`Med%`,`Hard%`, batter, Pos, height, weight, WAR, wRC, `wRC+`)%>%
  mutate(game_year = Season, player_name = Name)%>%
  select(-Season, -Name, -player_name)%>%
  filter(!is.na(batter))
  
```

# Bat Speed Aging Curve 

Exit Velocity Equation from Alan Nathan:

$ev = ea*vball + (1+ea)*vbat$


$vbat = (ev - ea*vball)/(1+ea)$


##Highest Bat Speeds 

```{r Calculating bat speed}
max_evs<-read_csv("max_evs.csv")%>%
  distinct()

swing_speeds_all<-max_evs%>%
  
  # need pitch speed for the bat speed equation 
  
  filter(!is.na(release_speed))%>%
  
  # Alan Nathan found pitch speed decreases 8.4% by time reaches plate. Assuming
  # ea = 0.2, the maximum, "barreled" "flush" contact.
  
  mutate(v_ball = 0.916*release_speed,
        
         ea = .20,
         bat_speed = (launch_speed-(ea*v_ball))/(1+ea))%>%
  
  # joining to include woba as well as age, height, position metrics into
  # dataset.
  
  left_join(metrics, by = c("game_year", "batter"))


avg_speeds_indiv<-swing_speeds_all%>%
  group_by(game_year, player_name)%>%
  
  # extreme values and outliers that happen to fall in the window of maximum
  # exit velo. Blast Motion reports swing speeds for MLB 65-85.
  
  filter(bat_speed >= 65)%>%
  
  # various summary statistics for each player's bat speed 
  
  mutate(avg_speed = mean(bat_speed), 
         med_speed = median(bat_speed), 
         avg_ev = mean(launch_speed), 
         three_fourths = quantile(bat_speed, probs = 0.75),
         min = min(bat_speed), 
         max = max(bat_speed))%>%
  arrange(desc(avg_speed))%>%
  select(game_year, player_name, Age, avg_speed, three_fourths, avg_ev, med_speed, PA, wOBA, Pos, height, weight, WAR, wRC, `wRC+`)%>%
  unique()%>%
    filter(!is.na(Age))%>%

  # grouping RF and LF together bc of small sameple size.
  
  mutate(Pos = case_when(Pos %in% c("RF", "LF") ~ "Corner OF",
                         TRUE ~ Pos))%>%
  arrange(desc(avg_speed))

```

```{r min/max speeds}

# code to create tables for highest and lowest average bat speeds using head and
# tail functions

as_tibble(head(avg_speeds_indiv%>%
                 mutate(avg_bat_speed = avg_speed)%>%
                 select(-three_fourths, -med_speed, -avg_speed, -avg_ev, -Pos, -height, -weight, - WAR, -wRC), 10))%>%
  gt()%>%
  fmt_number(columns = "avg_bat_speed",decimals = 2)


as_tibble(tail(avg_speeds_indiv%>%
                 mutate(avg_bat_speed = avg_speed)%>%
                 select(-three_fourths, -med_speed, -avg_speed, -avg_ev, -Pos, -height, -weight, -WAR, -wRC), 10))%>%
  gt()%>%
  fmt_number(columns = "avg_bat_speed",decimals = 2)

```

```{r exploratory analysis}

# survivorship bias graphic 


avg_speeds_indiv%>%
  filter(Age < 38, Age >19) %>%
  ggplot(aes(x = Age, y = avg_speed)) + geom_point() + geom_smooth(method = 'gam', formula = y ~ s(x))
```

```{r}
avg_speeds_indiv%>%
  arrange(player_name, desc(game_year))%>%
  
  # joing previous season data 
  
  left_join(season_2, by = c("game_year", "player_name"))%>%
  
  # making sure the year and age is consecutive
  
  filter(!is.na(Age_t1), Age == Age_t1 + 1)
```



```{r general aging curve set up}

# need two consecutive seasons for delta method. dataset for joining current
# season to previous season numbers

season_2<-avg_speeds_indiv %>%
  mutate(game_year = game_year + 1)%>%
  select(-Pos)
colnames(season_2)[c(3:14)] = paste(colnames(season_2)[c(3:14)], 't1', sep = '_')

# bat_speed deltas 

indiv_delta<-avg_speeds_indiv%>%
  arrange(player_name, desc(game_year))%>%
  
  # joing previous season data 
  
  left_join(season_2, by = c("game_year", "player_name"))%>%
  
  # making sure the year and age is consecutive
  
  filter(!is.na(Age_t1), Age == Age_t1 + 1)%>%
  ungroup()%>%
  
  # creating age bins and the difference for each players bat speed year to year
  
  mutate(bins = paste(Age_t1, Age, sep = "/"),
         delta = avg_speed- avg_speed_t1,
         PA_hm = 2 / (1/PA+ 1/PA_t1))%>%
  group_by(bins, Age)%>%
  
  # average delta for each age bin
  
  summarise(n = n(),
            sum = sum(delta),
            stat_diff = weighted.mean(delta, PA_hm, na.rm=TRUE),
         avg_delta = mean(delta))%>%
  ungroup()



# displaying the average deltas for age bins 

indiv_delta%>%
    filter(Age > 23, Age < 35)%>%
  arrange(Age)%>%
  gt()%>%fmt_number(columns = c("avg_delta"), decimals = 4)



# indiv_delta%>%
#     filter(Age > 22, Age < 35)%>%
#   arrange(Age)%>%
#   ungroup()%>%
#   mutate(csum = cumsum(avg_diff),
#          max = csum - max(csum))%>%
#   select(-age_avg, -sum, -max, -Age)%>%
#   gt()%>%fmt_number(columns = c("avg_diff", "csum"), decimals = 4)
```

```{r}

# aging curve cumulative sum graphic

csum_delta<-indiv_delta%>%
  
  #reasonable range 
  
    filter(Age > 20, Age < 39)%>%
  
  # need to arrange the data to perform cumulative sum
  
  arrange(Age)%>%
  ungroup()%>%
  
  # performing cumulative sum from the deltas. Use this to create the age curve.
  # I also rescale to make 0 the peak.
  
 mutate(csum = cumsum(stat_diff),
         max = csum - max(csum))%>%
         #delta_method = cumsum(stat_diff) - weighted.mean(cumsum(stat_diff), PA),
         #max_2 = delta_method - max(delta_method))%>%
  ggplot(aes(x = Age, y = max)) + 
  geom_point()+
  geom_smooth(method = "gam") +
  scale_x_continuous(breaks = seq(21,36,1), limits = c(21,36)) +
    labs(x = "Age", y = "Change in Bat Speed (MPH)",
       title = "Bat Speed Aging Curve (2015-2019)",
       subtitle = "Cumulative Sum, 0 = Peak Bat Speed, Window Size: 1/8",
       caption = "Red lines signifies >40 players in bin") + 
  
  # lines signifying range where I have the most data. 
  
    geom_vline(xintercept  = 24, linetype = "dotted", color = "red") + geom_vline(xintercept = 34, linetype = "dotted", color = "red")
  

# graphing changes between ages individually not as curves 

change_delta<-indiv_delta%>%
  
  # range for where I have at least 40 players in a bin 
  
  filter(Age > 23, Age < 35)%>%
  arrange(Age)%>%
  
  # columns for the deltas 
  ggplot()+
  geom_col(aes(x = bins, y = stat_diff, fill = stat_diff)) +  
  
  # coloring the deltas on a scale based on magnitude in positive or negative
  # direction
  
  scale_fill_continuous(low = "red", high = "green", guide = FALSE) + 
  labs(x = "Age", y = "Avg Change in Bat Speed (MPH)",
       title = "Average Change in Bat Speed By Age (2015-2019)") 


change_delta
csum_delta

cowplot::plot_grid(change_delta, csum_delta)



```

```{r GAM }


avg_speeds_indiv_2<-swing_speeds_all%>%
  group_by(game_year, player_name)%>%
  
  # extreme values and outliers that happen to fall in the window of maximum
  # exit velo. Blast Motion reports swing speeds for MLB 65-85.
  
  filter(bat_speed >= 65)%>%
  
  # various summary statistics for each player's bat speed 
  
  mutate(avg_speed = mean(bat_speed), 
         med_speed = median(bat_speed), 
         avg_ev = mean(launch_speed), 
         three_fourths = quantile(bat_speed, probs = 0.75),
         min = min(bat_speed), 
         max = max(bat_speed))%>%
  arrange(desc(avg_speed))%>%
  select(game_year, player_name, Age, avg_speed, three_fourths, avg_ev, med_speed, PA, wOBA, Pos, height, weight, WAR, wRC, bbe)%>%
  unique()%>%
    filter(!is.na(Age))%>%

  # grouping RF and LF together bc of small sameple size.
  
  mutate(Pos = case_when(Pos %in% c("RF", "LF") ~ "Corner OF",
                         TRUE ~ Pos))%>%
  arrange(desc(avg_speed))%>%
  ungroup()%>%
  group_by(player_name)%>%
  mutate(career_mean = mean(avg_speed))


 gam.mod <- mgcv::gam(avg_speed ~ s(Age) + career_mean, 
                       data=avg_speeds_indiv_2 %>%filter(Age >= 21 & Age <= 41), weights=PA)

  year_preds <- tibble(Age = seq.int(21,41))
  year_preds$gam_across = predict(gam.mod, newdata=year_preds%>%mutate(career_mean = 
                                                    weighted.mean(avg_speeds_indiv_2$career_mean,avg_speeds_indiv_2$PA)))

  year_preds%>%
    mutate()
  ggplot(year_preds,aes(x = Age, y = gam_across))+geom_point()+geom_smooth()+scale_x_continuous(breaks = seq(21,41,1))+ labs(title = "Aging Curve using Gam Model", y = "Average Bat Speed")

```





```{r WRC setup}


indiv_delta<-avg_speeds_indiv%>%
  arrange(player_name, desc(game_year))%>%
  
  # joing previous season data 
  
  left_join(season_2, by = c("game_year", "player_name"))%>%
  
  # making sure the year and age is consecutive
  
  filter(!is.na(Age_t1), Age == Age_t1 + 1)%>%
  ungroup()%>%
  
  # creating age bins and the difference for each players bat speed year to year
  
  mutate(bins = paste(Age_t1, Age, sep = "/"),
         delta = `wRC+` - `wRC+_t1`,
    PA_hm = 2 / (1/PA+ 1/PA_t1))%>%
  group_by(bins, Age)%>%
  
  # average delta for each age bin
  
  summarise(n = n(),
            sum = sum(delta),
            stat_diff = weighted.mean(delta, PA_hm, na.rm=TRUE),
         avg_delta = mean(delta))%>%
  ungroup()
# displaying the average deltas for age bins 
indiv_delta%>%
    filter(Age > 23, Age < 35)%>%
  arrange(Age)%>%
  gt()%>%fmt_number(columns = c("avg_delta"), decimals = 4)
# indiv_delta%>%
#     filter(Age > 22, Age < 35)%>%
#   arrange(Age)%>%
#   ungroup()%>%
#   mutate(csum = cumsum(avg_diff),
#          max = csum - max(csum))%>%
#   select(-age_avg, -sum, -max, -Age)%>%
#   gt()%>%fmt_number(columns = c("avg_diff", "csum"), decimals = 4)
```

```{r WRC }
# aging curve cumulative sum graphic
csum_delta<-indiv_delta%>%
  
  #reasonable range 
  
    filter(Age > 22, Age < 36)%>%
  
  # need to arrange the data to perform cumulative sum
  
  arrange(Age)%>%
  ungroup()%>%
  
  # performing cumulative sum from the deltas. Use this to create the age curve.
  # I also rescale to make 0 the peak.
  
  mutate(csum = cumsum(stat_diff),
         max = csum - max(csum))%>%
  
  ggplot(aes(x = Age, y = max)) + 
  geom_point()+
  geom_smooth() +
  scale_x_continuous(breaks = seq(21,38,1)) +
    labs(x = "Age", y = "Change in WRC+",
       title = "WRC+ Aging Curve (2015-2019)",
       subtitle = "Cumulative Sum, 0 = Peak WRC+",
       caption = "Red lines signifies >40 players in bin") + 
  
  # lines signifying range where I have the most data. 
  
    geom_vline(xintercept  = 24, linetype = "dotted", color = "red") + geom_vline(xintercept = 34, linetype = "dotted", color = "red") + 
  scale_y_continuous(breaks = seq(-60,0,5))
  
# graphing changes between ages individually not as curves 
change_delta<-indiv_delta%>%
  
  # range for where I have at least 40 players in a bin 
  
  filter(Age > 23, Age < 35)%>%
  arrange(Age)%>%
  
  # columns for the deltas 
  ggplot()+
  geom_col(aes(x = bins, y = stat_diff, fill = stat_diff)) +  
  
  # coloring the deltas on a scale based on magnitude in positive or negative
  # direction
  
  scale_fill_continuous(low = "red", high = "green", guide = FALSE) + 
  labs(x = "Age", y = "Avg Change in Bat Speed (MPH)",
       title = "Average Change in Bat Speed By Age (2015-2019)") 
cowplot::plot_grid(change_delta, csum_delta)



csum_delta






```




```{r Position Curves}

# Bat Speed Aging Curves by position 

# perform same steps of joining data from previous season, bining by age, and
# finding the deltas

avg_speeds_indiv%>%
  arrange(player_name, desc(game_year))%>%
  group_by(player_name)%>%
  left_join(season_2, by = c("game_year", "player_name"))%>%
  filter(!is.na(Age_t1), Age == Age_t1 + 1)%>%
  mutate(bins = paste(Age, Age_t1, sep = "/"),
         dif = avg_speed - avg_speed_t1,
            PA_hm = 2 / (1/PA+ 1/PA_t1))%>% 
  
  # limiting the age range because less data now that I split dataset by position 
  
  filter(Age > 24, Age< 34, Pos != "P")%>%
  

  # adding position to the group by to find average changes per age bin.
  
  group_by(bins, Age, Pos)%>%
  summarise(n = n(),
         sum = sum(dif),
         avg_diff = mean(dif),
         stat_diff = weighted.mean(dif, PA_hm, na.rm=TRUE))%>%
   ungroup()%>%
  arrange(Pos, Age)%>%
  group_by(Pos)%>%
  mutate(csum = cumsum(stat_diff),
         max = csum - max(csum))%>%
  ggplot(aes(x = Age, y = max, color = Pos)) + 
  geom_point()+
  geom_smooth(se = FALSE) +
  scale_x_continuous(breaks = seq(20,42,1)) + 
  labs(x = "Age", y = "Avg Change in Bat Speed (MPH)",
       title = "Average Change in Bat Speed (15-19)") + 
  facet_wrap(~Pos) + 
  theme(axis.text.x = element_text(angle = 90)) +
  scale_y_continuous(limits = c(-2,0), breaks = seq(-2,0,0.2))


```


```{r Heights Curves}

# aging curves grouped by heights 

avg_speeds_heights<-avg_speeds_indiv%>%
  
  # did not know exactly where to draw the lines for height groupings. There are
  # not that many players above 6'4 thus I also added the "6'3-" category, which
  # overlaps with 6'4-, but has a greater sample size
  
  mutate(height_group = case_when(height < 73 ~ "-6'0",
                            height < 76 & height >= 73 ~ "6'1 - 6'3",
                            height >= 76 ~ "6'4-"))%>%
  bind_rows(avg_speeds_indiv%>%mutate(height_group = case_when(height >= 75 ~ "6'3-")))


# joining dataset 

season_2_heights<-avg_speeds_heights %>%
  mutate(game_year = game_year + 1)%>%
  select(-height_group, - height, -weight)

colnames(season_2_heights)[c(3:9)] = paste(colnames(season_2_heights)[c(3:9)], 't1', sep = '_')

# same steps for the aging curves as above 

avg_speeds_heights%>%
  arrange(player_name, desc(game_year))%>%
  group_by(player_name)%>%
  left_join(season_2_heights, by = c("game_year", "player_name"))%>%
  filter(!is.na(Age_t1), Age == Age_t1 + 1)%>%
  mutate(bins = paste(Age, Age_t1, sep = "/"),
         dif = avg_speed - avg_speed_t1,
         PA_hm = 2 / (1/PA+ 1/PA_t1))%>% 
  
  # Nas were created in making height groups, making sure only keeping the 4
  # groupings I made
  
  filter(Age > 22, Age<35, height_group%in% c("-6'0", "6'1 - 6'3", "6'3-", "6'4-"))%>%
  group_by(bins, Age, height_group)%>%
  summarise(n = n(),
         sum = sum(dif),
         avg_diff = mean(dif),
         stat_diff = weighted.mean(dif, PA_hm, na.rm=TRUE))%>%
   ungroup()%>%
  arrange(height_group, Age)%>%
 group_by(height_group)%>%
  mutate(csum = cumsum(stat_diff),
         max = csum - max(csum))%>%
  ggplot(aes(x = Age, y = max)) + 
  geom_point()+
  geom_smooth(se = FALSE) +
  scale_x_continuous(breaks = seq(20,42,1)) + 
  labs(x = "Age", y = "Avg Change in Bat Speed (MPH)",
       title = "Bat Speed Aging Curve By Height (2015-2019)") + 
  facet_wrap(~height_group) + 
  theme(axis.text.x = element_text(angle = 90)) +
  scale_y_continuous(limits = c(-2,0), breaks = seq(-2,0,0.2))
```



###imputed
```{r Imputing Data}

# I wanted to try to impute data to see if any different trends emerge. The
# imputation will help for 2015 where there is no prior season for bining, thus all the
# data is not used. Also any injured seasons will be imputed


season_2_impute<-avg_speeds_indiv%>%
  mutate(Age = Age + 1)%>%
  ungroup()%>%
  select(- game_year, -Pos, - height, -weight, -(9:14))
colnames(season_2_impute)[c(3:8)] = paste(colnames(season_2_impute)[c(3:8)], 't1', sep = '_')

# dataset before imputing. The values that will be imputed are avg_speed_t1, the
# speed from previous season to be able to find deltas for players missing the
# previous season in consecutive sesaon pairings

before_impute<-avg_speeds_indiv%>%
  select(-(9:14))%>%
  arrange(player_name, desc(game_year))%>%
  group_by(player_name)%>%
  left_join(season_2_impute, by = c("Age", "player_name"))%>%
  ungroup()%>%
  #mutate(PA_t1 = case_when(is.na(PA_t1) ~ PA,
  #                         TRUE ~ PA_t1))%>%
  select(-contains("wRC"))
            
library(mice)

# imputation. excluding all the other variables as only want to impute avg_speed_t1

imputed<- mice(before_impute%>%select(-player_name, -three_fourths_t1, -avg_ev_t1, -med_speed_t1))


# mice attempts 5 different ways to impute for missing values and returns 5
# separate datasets. I combine these 5 into 1 dataset.

new_imp<-map_dfr(1:5, ~complete(imputed, action = .x))

# with the 5 imputed datsets I take the mean across all 5 imputations.

new_imp<-before_impute%>%
  bind_rows(before_impute)%>%
  bind_rows(before_impute)%>%
  bind_rows(before_impute)%>%
  bind_rows(before_impute)%>%
  select(player_name)%>%
  bind_cols(new_imp)%>%
  group_by(player_name, game_year, Age)%>%
  summarise_all(mean)%>%
  mutate(Age_t1 = Age -1)
  

# calculating average differences between age bins 

imputed_delta<-new_imp%>%
  arrange(player_name, desc(game_year))%>%
  group_by(player_name)%>%
  filter(!is.na(Age_t1), Age == Age_t1 + 1)%>%
  ungroup()%>%
  mutate(bins = paste(Age_t1, Age, sep = "/"),
         dif = avg_speed - avg_speed_t1,
         player_name = player_name,
         PA_hm = 2 / (1/PA+ 1/PA_t1))%>%
  group_by(bins, Age)%>%
  summarise(n = n(),
            sum = sum(dif),
         avg_diff = mean(dif), 
         stat_diff = weighted.mean(dif, PA_hm, na.rm=TRUE))%>%
  ungroup()



# bat speed aging curve 

csum_impute<-imputed_delta%>%
    filter(Age > 21, Age < 39)%>%
  arrange(Age)%>%
  ungroup()%>%
   mutate(csum = cumsum(stat_diff),
         max = csum - max(csum))%>%
  ggplot(aes(x = Age, y = max)) + geom_point()+geom_smooth(method = "gam", se = FALSE) +
  scale_x_continuous(breaks = seq(22,40,1)) +
   scale_y_continuous(limits = c(-1.4,0), breaks = seq(-1.4,0,0.2)) + 
  labs(x = "Age", y = "Csum Bat Speed (MPH)",
       title = "Cumulative Sum Bat Speed (15-19)")


# changes per bin graph 

change_impute<-imputed_delta%>%
  filter(Age > 21, Age < 39)%>%
  arrange(Age)%>%
  ggplot()+geom_col(aes(x = Age, y = stat_diff, fill = stat_diff)) +   scale_fill_continuous(low = "red", high = "green", guide = FALSE) + 
  scale_x_continuous(breaks = seq(22,38,1)) +
  labs(x = "Age", y = "Avg Change in Bat Speed (MPH)",
       title = "Average Change in Bat Speed By Age (2015-2019)") 
  

cowplot::plot_grid(change_impute, csum_impute)

csum_impute


```


```{r Starting Bat Speed Analysis}

# Analysis of changes to bat speed giving starting point when entering the league 

bat_group<-avg_speeds_indiv%>%
  arrange(player_name, game_year)%>%
  left_join(season_2, by = c("game_year", "player_name"))%>%
  filter(!is.na(Age_t1), Age == Age_t1 + 1)%>%
  group_by(player_name)%>%
  
  # finding the first year each player appears in the dataset
  
  mutate(min_age = min(Age_t1))%>%
  
  # only keeping minimum ages 23-25. I have sufficient data in this range and I
  # assume these are ages most rookies entire the MLB
  
  filter(min_age >= 23 & min_age <= 25)%>%
  ungroup()


quantile(bat_group$avg_speed_t1)

# where the players in the bat_groups started out in terms of bat speed 

start_speeds<-bat_group%>%
  
  # taking a look at their first season in dataset 
  
  filter(Age_t1 == min_age)%>%
  group_by(player_name)%>%
  
  # dividing the dataset into two. Above and below median of the batspeeds when
  # first entiring the league. Median ~71.5 MPH
  
summarise(speed_group = case_when(avg_speed_t1 <= median(bat_group$avg_speed_t1) ~ "Below Median ",
       avg_speed_t1 > median(bat_group$avg_speed_t1) ~ "Above Median"))



# grouping by bins and finding deltas for each player and then finding average
# for each speed grouping

starting_deltas<-bat_group%>%
  left_join(start_speeds, by = "player_name")%>%
  filter(!is.na(Age_t1), Age == Age_t1 + 1)%>%
  mutate(bins = paste(Age, Age_t1, sep = "/"),
         dif = avg_speed - avg_speed_t1,
          PA_hm = 2 / (1/PA+ 1/PA_t1))%>% 
  group_by(bins, Age, speed_group)%>%
  summarise(n = n(),
         sum = sum(dif),
         avg_diff = mean(dif),
         stat_diff = weighted.mean(dif, PA_hm, na.rm=TRUE))%>%
   ungroup()
  
# cumulative sum aging curve 
  
  starting_csum<- starting_deltas%>%
    group_by(speed_group)%>%
    mutate(csum = cumsum(stat_diff))%>%
    filter(Age < 29)%>%
    ggplot(aes(x = Age, y = csum)) + geom_smooth(se = FALSE) +
    labs(x = "Age", y = "Avg Change in Bat Speed (MPH)",
         title = "Bat Speed Grouped By First Recorded Bat Speed") + 
    facet_wrap(~speed_group) + 
    theme(axis.text.x = element_text(angle = 90))  + scale_y_continuous(breaks = seq(-0.5,1.5,0.25))
    
  # age bin changes faceted by starting group graph
  
  starting_changes<- starting_deltas%>%
      arrange(speed_group, Age)%>%
    arrange(Age)%>%
      filter(Age < 29)%>%
    ggplot()+geom_col(aes(x = bins, y = stat_diff, fill = stat_diff)) +   scale_fill_continuous(low = "red", high = "green", guide = FALSE) + 
    labs(x = "Age", y = "Avg Change in Bat Speed (MPH)") + facet_wrap(~speed_group)
    
  starting_csum
  starting_changes
  cowplot::plot_grid(starting_csum, starting_changes)  
  
```

